title: DroneCAN
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "specificationxxx/"

exclude:
  - "specification/Specification/dsdl/*.md"
  - "specification/Specification/dsdl/uavcan/*.md"

